services:
  - type: web
    name: alera-ai
    env: python
    region: frankfurt   # or ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alera.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: alera-db
          property: connectionString

databases:
  - name: alera-db
    plan: free
